server:
  port: 8080

apache:
  rocketmq:
    consumer:
      PushConsumer: PushConsumer
    producer:
      producerGroup: Producer
    namesrvAddr: localhost:9876

spring:
  thymeleaf:
    cache: false
    mode: HTML5
